### ISSUE TITLE
Socket timing out

### ISSUE THREAD

**Issue by LucasPucher** [sepr88/CarND-Capstone#26]
My socket is timing out one minute after starting the simulator. Tried with camera off and on and it is timing out. Does anybody have the problem?
No clue what is the problem.

Error dump:

(3868) wsgi exited, is_accepting=True
Traceback (most recent call last):
  File "/home/lucas/development/CarND-Capstone/ros/src/styx/server.py", line 69, in <module>
    eventlet.wsgi.server(eventlet.listen(('', 4567)), app)
  File "/home/lucas/.local/lib/python2.7/site-packages/eventlet/wsgi.py", line 983, in server
    client_socket, client_addr = sock.accept()
  File "/home/lucas/.local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 230, in accept
    self._trampoline(fd, read=True, timeout=self.gettimeout(), timeout_exc=_timeout_exc)
  File "/home/lucas/.local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 210, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/home/lucas/.local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 159, in trampoline
    return hub.switch()
  File "/home/lucas/.local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 298, in switch
    return self.greenlet.switch()
socket.timeout: timed out
[styx_server-2] process has died [pid 3868, exit code 1, cmd /home/lucas/development/CarND-Capstone/ros/src/styx/server.py __name:=styx_server __log:=/home/lucas/.ros/log/cb3fb09e-a411-11e9-9bd9-34f64b5e8747/styx_server-2.log].
log file: /home/lucas/.ros/log/cb3fb09e-a411-11e9-9bd9-34f64b5e8747/styx_server-2*.log

**Comment by sepr88** [comment]
check out https://knowledge.udacity.com/questions/12389

**Comment by LucasPucher** [comment]
Magically working after ubuntu reboot.
